(def inventors {"Lisp", "McCarthy", "Clojure", "Hickey"})
(println (type inventors))
(println (inventors "Lisp"))
(println (inventors :Lisp))
(println (inventors "Foo"))
(println (get inventors "Lisp" "default value"))
(println (get inventors "Foo" "default value"))

(def inventors {:Lisp "McCarthy", :Clojure "Hickey"})
(println (type inventors))
(println (inventors "Lisp"))
(println (inventors :Lisp))
(println (inventors :Foo))
(println (get inventors :Lisp "default value"))
(println (get inventors :Foo "default value"))